export type ApartmentTransaction = {
  id: string;
  apartmentId: string;
  dealDate: string;
  dealYear: number;
  dealMonth: number;
  dealDay: number;
  exclusiveAreaM2: number;
  floor?: number | null;
  dealAmountKrw: number;
  dealAmountManwon: number;
  apartmentNameFromSource?: string | null;
  addressFromSource?: string | null;
  cancelYn?: string | null;
  cancelDate?: string | null;
  sourceName: string;
  sourceRef?: string;
  sourceHash: string;
  fetchedAt: string;
  confidenceLevel: "high" | "medium" | "low" | "manual" | "unknown";
};
